[toolchain]
anchor_version = "1.2.0"
solana_version = "4.1.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
mutav = "8scC79jkU7SPM9v6M4nB833R8EeqKknfwdRdjn73Qqv9"
mutav_adapter_mock = "HnDdop5PFqvVKZNujsuakwm2K5GskAUk1GxzbDSdGuMo"

[programs.localnet]
mutav = "8scC79jkU7SPM9v6M4nB833R8EeqKknfwdRdjn73Qqv9"
mutav_adapter_mock = "HnDdop5PFqvVKZNujsuakwm2K5GskAUk1GxzbDSdGuMo"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/mutav", "programs/mutav-adapter-mock"]

[scripts]
test = "RUST_TEST_THREADS=4 cargo test -p mutav-tests"

[hooks]
