/**
 * Task 12, step 5: the investor allowlist. Builds the Merkle tree of the
 * config's `allowlist` (encoding in clients/js/src/allowlist.ts, matching
 * the program), writes every owner's proof for mutav-app to serve, and the
 * `set_allowlist_root` proposal.
 *
 *   bun scripts/devnet/allowlist.ts --config <deploy.json> --proofs <proofs.json> --out <proposal.json>
 *
 * `--write-fixture` regenerates tests/fixtures/client/allowlist-proofs.json,
 * the trees the program's own `allowlist::verify` checks in
 * tests/tests/client_vectors.rs.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { address, createNoopSigner, type Address } from '@solana/kit';
import { buildAllowlist } from '../../clients/js/src';
import { parseArgs, REPO_ROOT, req, type Args } from './lib/cli';
import { composeSetAllowlistRoot } from './lib/compose';
import { loadConfig } from './lib/config';
import { assertOnlyVaultSigns, toPayload, writePayload } from './lib/proposal';
import { assertAdminIsVault } from './init';

const hex = (b: Uint8Array) => Buffer.from(b).toString('hex');

export async function proofsJson(owners: Address[]) {
  const t = await buildAllowlist(owners);
  return {
    root: hex(t.root),
    proofs: [...t.proofs.entries()]
      .sort(([a], [b]) => (a < b ? -1 : 1))
      .map(([owner, proof]) => ({ owner, proof: proof.map(hex) })),
  };
}

async function writeFixture() {
  const vectors = JSON.parse(readFileSync(join(REPO_ROOT, 'tests', 'fixtures', 'client', 'vectors.json'), 'utf8'));
  const owners: Address[] = vectors.allowlist.leaves.map((l: { owner: string }) => address(l.owner));
  const trees = [];
  for (const n of [1, 2, 3, 4, 5]) trees.push(await proofsJson(owners.slice(0, n)));
  const path = join(REPO_ROOT, 'tests', 'fixtures', 'client', 'allowlist-proofs.json');
  writeFileSync(
    path,
    JSON.stringify({ _comment: 'Generated by scripts/devnet/allowlist.ts --write-fixture. Verified by tests/tests/client_vectors.rs.', trees }, null, 2) + '\n',
  );
  console.log(`wrote ${path}`);
}

export async function main(args: Args) {
  if (args['write-fixture']) return writeFixture();
  const cfg = loadConfig(req(args, 'config'));
  await assertAdminIsVault(cfg);
  const proofs = await proofsJson(cfg.allowlist);
  writeFileSync(req(args, 'proofs'), JSON.stringify(proofs, null, 2) + '\n');
  console.log(`wrote proofs for ${proofs.proofs.length} owner(s); root ${proofs.root}`);
  const root = Uint8Array.from(Buffer.from(proofs.root, 'hex'));
  const ix = await composeSetAllowlistRoot(cfg, root, createNoopSigner(cfg.admin));
  const payload = toPayload({ title: `MUTAV: set allowlist root ${proofs.root}`, cluster: cfg.cluster, multisig: cfg.squads.multisig, vaultIndex: cfg.squads.vaultIndex, vault: cfg.admin }, [ix]);
  assertOnlyVaultSigns(payload);
  writePayload(req(args, 'out'), payload);
}

if (import.meta.main) await main(parseArgs());
